modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="dranium"
version="1.0.002"
displayName="Dranium"
credits="Sorry mark... I was bored."
displayURL="https://github.com/BulutCorbaci/Dranium-Forge"
authors="Bemzey, BulutCorbaci"
description='''
New ores and more stuff!
'''

[[dependencies.dranium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




